---
- name: Disable and Mask firewalld
  hosts: all
  become: yes  # Run tasks as root

  tasks:
    - name: Stop firewalld service
      systemd:
        name: firewalld
        state: stopped
        enabled: no

    - name: Ensure firewalld service file is removed if blocking masking
      ansible.builtin.file:
        path: /etc/systemd/system/firewalld.service
        state: absent
    
    - name: Mask firewalld service
      ansible.builtin.systemd:
        name: firewalld
        masked: true


- name: Set up insecure registry for Docker
  hosts: node1,node2,node3
  become: yes

  vars:
    insecure_registry: "registry.kube-system.svc.cluster.local:5000"

  tasks:

    - name: Ensure /etc/docker directory exists
      file:
        path: /etc/docker
        state: directory
        mode: '0755'

    - name: Create /etc/docker/daemon.json if not exists
      file:
        path: /etc/docker/daemon.json
        state: touch
        mode: '0644'

    - name: Configure Docker daemon.json for insecure registry
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "insecure-registries": ["{{ insecure_registry }}"]
          }
        owner: root
        group: root
        mode: '0644'

